#!/usr/bin/env bash
# Create a backup of the original hosts file with sudo
sudo cp /etc/hosts /etc/hosts.bak
# Configure localhost resolves to 127.0.0.2 in the backup file using sudo
sudo sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts.bak
# Configure facebook.com to resolve to 8.8.8.8 in the backup file using sudo
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts.bak
# Replace old hosts file with new one
cp -f /etc/hosts.bak /etc/hosts